server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Sayhello67!@
  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create  #create update none
      default_batch_fetch_size: 500
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token_exp: ${JWT_ACESS_TOKEN_EXP}
  refresh-token_exp: ${JWT_REFRESH_TOKEN_EXP}

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
