server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 500
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token_exp: ${JWT_ACESS_TOKEN_EXP}
  refresh-token_exp: ${JWT_REFRESH_TOKEN_EXP}

kakao:
  iss: ${KAKAO_ISS}
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-url: ${KAKAO_REDIRECT_URL}
  app-key: ${KAKAO_APP_KEY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      instance-profile: false
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      auto: false
      static: ${S3_REGION}
    stack:
      auto: false

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

